// Try Catch

const num1 = 1;
const num2 = 2;

console.log(num1);

try {
  console.log(num3);
} catch (error) {
  console.log(error);
}
console.log(num2);
